FROM registry.access.redhat.com/ubi8/ubi
ARG ECOSYSTEM_VERSION=python3
LABEL org.opencontainers.image.source https://github.com/fabric8-analytics/crda-images
RUN yum install -y $ECOSYSTEM_VERSION; yum clean all && ln -s /usr/bin/python3 /usr/bin/python

RUN rpm -i https://github.com/fabric8-analytics/cli-tools/releases/download/v0.1.2/crda_0.1.2_Linux-64bit.rpm

RUN yum install jq -y

ENV AUTH_TOKEN=''
ENV CRDA_KEY=''
ENV HOST=''

COPY scripts/python/crda.sh /
RUN chmod +x /crda.sh
